### ISSUE TITLE
ValueError: unknown url type: 'rosdistro/index.yaml'

### ISSUE THREAD

**Issue by git-afsantos** [rosin-project/rosinstall_generator_time_machine#2]
When using the script with the following arguments,

```bash
$ time_machine https://github.com/yujinrobot/kobuki/issues/246 1c141a5 kinetic kobuki_driver deps_1c141a5.rosinstall
```

I encountered a `ValueError`. Here follows the trace and full output.

```
Need to clone rosdistro ..
Cloning into 'rosdistro'...
remote: Counting objects: 113267, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 113267 (delta 3), reused 2 (delta 0), pack-reused 113255
Receiving objects: 100% (113267/113267), 40.37 MiB | 1.72 MiB/s, done.
Resolving deltas: 100% (72374/72374), done.
Checking connectivity... done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Retrieving issue 'created_at' property for: https://github.com/yujinrobot/kobuki/issues/246
Found: 2013-04-05T09:27:36Z
Determined rosdistro commit: 18eac03e3165192222bdb42ad9401b9ddbd9a7fc
Going back in rosdistro's history
Switched to a new branch 'bughunt_1c141a5'
Building cache ..
Traceback (most recent call last):
  File "/home/andre/robust/bin/rosdistro_build_cache", line 115, in <module>
    main()
  File "/home/andre/robust/bin/rosdistro_build_cache", line 90, in main
    ignore_errors=args.ignore_errors)
  File "/home/andre/robust/lib/python3.5/site-packages/rosdistro/distribution_cache_generator.py", line 56, in generate_distribution_caches
    index = get_index(index)
  File "/home/andre/robust/lib/python3.5/site-packages/rosdistro/__init__.py", line 101, in get_index
    yaml_str = load_url(url)
  File "/home/andre/robust/lib/python3.5/site-packages/rosdistro/loader.py", line 48, in load_url
    fh = urlopen(url, timeout=timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 451, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'rosdistro/index.yaml'
```

Any idea of what might be going on?

**Comment by gavanderhoorn** [comment]
See also the readme btw, where this is mentioned at least twice ;)

> ### Limitations
> 
> The current implementation can only go back to 25th of January, 2014 [..]

**Comment by git-afsantos** [comment]
Oh, right! Now I feel dumb, didn't even think of looking at the date.

I will move on to another bug, then.

**Comment by gavanderhoorn** [comment]
Could you perhaps open an issue over at [robust-rosin/robust/issues](https://github.com/robust-rosin/robust/issues) to track this? I'd like to track bugs that are too old (right now) so I have some ready to use testcases if/when I start to work on this.

Thanks.

**Comment by gavanderhoorn** [comment]
@git-afsantos: I'm going to close this as the error you included in the OP cannot (well .. should not) happen any more. The script checks to make sure you don't attempt to go back too far.

#8 has extended the date we can go back to, to `2013-04-22T13:14:47-0700`, which seems to allow for recreating quite a nr of our selected bugs.

Bugs that are older are tracked on the `robust-rosin/robust` issue tracker, so I'll close this issue.
