### ISSUE TITLE
Contiously Asking for GitHub Credentials

### ISSUE THREAD

**Issue by tobiasduerschmid** [rosin-project/rosinstall_generator_time_machine#21]
When I want to go back to indigo for 15th of April 2016, time machine asks me for my github credentials when building the cache. When I provide them, it just keeps asking again and again. 

```
$ ./rosinstall_generator_tm.sh '2016-04-15T19:41:20' indigo > deps.rosinstall
Requested timepoint: '2016-04-15T19:41:20' (1460763680)
Resetting local rosdistro clone ..
Previous HEAD position was 76aea9224 Revert "Adding uavc_v4lctl to documentation index for distro jade" (#11117)
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
Determined rosdistro commit: 76aea922 (authored: 1460755828)
Reverting to ros/rosdistro@76aea922
Determining closest rosdistro cache ..
Base cache for new cache: /home/<user>/.robust-rosin/rgtm/rgtm_rosdistro_caches/1460093685
Will store new cache in: /home/<user>/.robust-rosin/rgtm/rgtm_rosdistro_caches/1460755828
Building cache ..
Build cache for "indigo"
- trying to use local cache
- trying to fetch cache
- update cache
  - updated 'doc' entry for repository 'fzi_icl_core'
  - updated 'source' entry for repository 'fzi_icl_core'
  - updated 'source' entry for repository 'jsk_apc'
  - updated 'doc' entry for repository 'qwt_dependency'
  - updated 'source' entry for repository 'qwt_dependency'
  - updated 'doc' entry for repository 'robotican'
  - updated 'source' entry for repository 'robotican'
  - updated 'source' entry for repository 'rosconsole_bridge'
  - updated 'doc' entry for repository 'rqt_paramedit'
  - updated 'source' entry for repository 'rqt_paramedit'
  - updated 'doc' entry for repository 'screenrun'
  - updated 'source' entry for repository 'screenrun'
  - updated 'doc' entry for repository 'teb_local_planner_tutorials'
  - updated 'source' entry for repository 'teb_local_planner_tutorials'
  - updated 'doc' entry for repository 'uavc_v4lctl'
  - updated 'source' entry for repository 'uavc_v4lctl'
- removing invalid release package cache entries.
- fetch missing release manifests
.............  - updated manifest of package 'actionlib_lisp' to version '0.2.6'
................................................................................................  - updated manifest of package 'bus_server' to version '0.1.1'
.........................................................  - updated manifest of package 'checkerboard_detector' to version '0.3.21'
...  - updated manifest of package 'cl_tf' to version '0.2.6'
.  - updated manifest of package 'cl_tf2' to version '0.2.6'
.  - updated manifest of package 'cl_transforms' to version '0.2.6'
.  - updated manifest of package 'cl_transforms_stamped' to version '0.2.6'
.  - updated manifest of package 'cl_urdf' to version '0.2.6'
..  - updated manifest of package 'cl_utils' to version '0.2.6'
............................................................................................................................................................................................  - updated manifest of package 'dji_sdk' to version '0.1.6'
.  - updated manifest of package 'dji_sdk_demo' to version '0.1.6'
.  - updated manifest of package 'dji_sdk_dji2mav' to version '0.1.6'
.  - updated manifest of package 'dji_sdk_lib' to version '0.1.6'
.  - updated manifest of package 'dji_sdk_web_groundstation' to version '0.1.6'
....................................................................................................................................  - updated manifest of package 'fetch_tools' to version '0.1.4'
...........................  - updated manifest of package 'fzi_icl_core' to version '1.0.1'
.....................................................................................................................................................................  - updated manifest of package 'imagesift' to version '0.3.21'
....  - updated manifest of package 'imu_monitor' to version '1.6.16'
....................................................................  - updated manifest of package 'jsk_2015_05_baxter_apc' to version '0.2.4'
.  - updated manifest of package 'jsk_2016_01_baxter_apc' to version '0.2.4'
..  - updated manifest of package 'jsk_apc' to version '0.2.4'
.  - updated manifest of package 'jsk_apc2015_common' to version '0.2.4'
.  - updated manifest of package 'jsk_apc2016_common' to version '0.2.4'
........................  - updated manifest of package 'jsk_pcl_ros' to version '0.3.21'
.  - updated manifest of package 'jsk_pcl_ros_utils' to version '0.3.21'
..  - updated manifest of package 'jsk_perception' to version '0.3.21'
.....  - updated manifest of package 'jsk_recognition' to version '0.3.21'
.  - updated manifest of package 'jsk_recognition_msgs' to version '0.3.21'
.  - updated manifest of package 'jsk_recognition_utils' to version '0.3.21'
...............  - updated manifest of package 'katana' to version '1.0.5'
.  - updated manifest of package 'katana_arm_gazebo' to version '1.0.5'
.  - updated manifest of package 'katana_description' to version '1.0.5'
.  - updated manifest of package 'katana_driver' to version '1.0.5'
.  - updated manifest of package 'katana_gazebo_plugins' to version '1.0.5'
.  - updated manifest of package 'katana_moveit_ikfast_plugin' to version '1.0.5'
.  - updated manifest of package 'katana_msgs' to version '1.0.5'
.  - updated manifest of package 'katana_teleop' to version '1.0.5'
.  - updated manifest of package 'katana_tutorials' to version '1.0.5'
...........  - updated manifest of package 'kni' to version '1.0.5'
.................................................................................................................................................  - updated manifest of package 'moveit_core' to version '0.7.1'
.....  - updated manifest of package 'moveit_msgs' to version '0.7.1'
....................................................................................................................................................................................WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
..................................  - updated manifest of package 'oxford_gps_eth' to version '0.0.4'
......................................................................  - updated manifest of package 'pr2_bringup' to version '1.6.16'
...  - updated manifest of package 'pr2_camera_synchronizer' to version '1.6.16'
....  - updated manifest of package 'pr2_computer_monitor' to version '1.6.16'
.  - updated manifest of package 'pr2_controller_configuration' to version '1.6.16'
..........  - updated manifest of package 'pr2_ethercat' to version '1.6.16'
...........................................  - updated manifest of package 'pr2_robot' to version '1.6.16'
.  - updated manifest of package 'pr2_run_stop_auto_restart' to version '1.6.16'
...........................................  - updated manifest of package 'qt_paramedit' to version '1.0.0'
....  - updated manifest of package 'qwt_dependency' to version '1.0.0'
....................  - updated manifest of package 'resized_image_transport' to version '0.3.21'
............................................................................................................................................  - updated manifest of package 'rosdoc_lite' to version '0.2.6'
..............................  - updated manifest of package 'roslisp' to version '1.9.20'
.  - updated manifest of package 'roslisp_common' to version '0.2.6'
..  - updated manifest of package 'roslisp_utilities' to version '0.2.6'
...................................................................  - updated manifest of package 'rqt_ez_publisher' to version '0.3.1'
.............  - updated manifest of package 'rqt_paramedit' to version '1.0.0'
......................................................................................  - updated manifest of package 'screenrun' to version '1.0.2'
.........................  - updated manifest of package 'sick_tim' to version '0.0.7'
..............................................................................................................................  - updated manifest of package 'teb_local_planner' to version '0.3.1'
.  - updated manifest of package 'teb_local_planner_tutorials' to version '0.0.1'
.....Username for 'https://github.com': tobiasduerschmid
Password for 'https://tobiasduerschmid@github.com':
Username for 'https://github.com': tobiasduerschmid
Password for 'https://tobiasduerschmid@github.com':
Username for 'https://github.com': ^C.Username for 'https://github.com': ^CTraceback (most recent call last):
  File "/rgtm/post141/bin/rosdistro_build_cache", line 116, in <module>
    main()
  File "/rgtm/post141/bin/rosdistro_build_cache", line 90, in main
    ignore_errors=args.ignore_errors)
  File "/rgtm/post141/local/lib/python2.7/site-packages/rosdistro/distribution_cache_generator.py", line 68, in generate_distribution_caches
    ignore_errors=ignore_errors)
  File "/rgtm/post141/local/lib/python2.7/site-packages/rosdistro/distribution_cache_generator.py", line 101, in generate_distribution_cache
    package_xml = dist.get_release_package_xml(pkg_name)
  File "/rgtm/post141/local/lib/python2.7/site-packages/rosdistro/distribution.py", line 77, in get_release_package_xml
    package_xml = mp(self._distribution_file.name, repo, pkg_name)
  File "/rgtm/post141/local/lib/python2.7/site-packages/rosdistro/manifest_provider/cache.py", line 96, in __call__
    package_xml = sanitize_xml(mp(dist_name, repo, pkg_name))
  File "/rgtm/post141/local/lib/python2.7/site-packages/rosdistro/manifest_provider/github.py", line 65, in github_manifest_provider
    if not repo.has_remote_tag(release_tag):
  File "/rgtm/post141/local/lib/python2.7/site-packages/rosdistro/repository_specification.py", line 66, in has_remote_tag
    return tag in self.remote_tags
  File "/rgtm/post141/local/lib/python2.7/site-packages/rosdistro/repository_specification.py", line 83, in remote_tags
    for name, sha in self.remote_refs.items():
  File "/rgtm/post141/local/lib/python2.7/site-packages/rosdistro/repository_specification.py", line 71, in remote_refs
    result = Git().command('ls-remote', self.url)
  File "/rgtm/post141/local/lib/python2.7/site-packages/rosdistro/vcs.py", line 53, in command
    return _run_command((self._client_executable,) + args, self.cwd)
  File "/rgtm/post141/local/lib/python2.7/site-packages/rosdistro/vcs.py", line 71, in _run_command
    output, _ = proc.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

```

**Comment by gavanderhoorn** [comment]
This is mentioned/explained in the [readme](https://github.com/rosin-project/rosinstall_generator_time_machine/blob/c37a8b6d9f820394d976da155659f8c0075c5132/README.md):

> **Note**: be prepared to press <kbd>RET</kbd> or <kbd>ENTER</kbd> a few times for some repositories that no longer exist, or are now private repositories (and for which `git` would now need a password).

**Comment by gavanderhoorn** [comment]
That's just how Github "communicates" repositories don't exist or are no longer available.

It's a security "feature": you don't know whether the repository doesn't exist, or it's private.

**Comment by gavanderhoorn** [comment]
Closing, as this is not an issue with the time machine.

**Comment by gavanderhoorn** [comment]
And you don't need to enter your credentials.

Just press <kbd>Enter</kbd>.

Your username+pw are not going to bring back those repositories that disappeared.

**Comment by gavanderhoorn** [comment]
I've added this to the FAQ: c707bc52614531d32d86e9b3bfd870ffd3f239b4.

**Comment by gavanderhoorn** [comment]
Btw:

> `$ ./rosinstall_generator_tm.sh '2016-04-15T19:41:20' indigo > deps.rosinstall`

what are you trying to do exactly here?

`indigo` is not a package name. Does `rosinstall_generator` accept that?

It would be much more efficient to specify a specific *variant* or an actual package name.
